Use explicit and user-friendly configuration for public document repositories
metanorma/mn-samples-iso pull request #84
Opened 2023-09-02 21:40 UTC by CAMOBAP

### Related issues

 - https://github.com/metanorma/ci/issues/115
 - https://github.com/metanorma/mn-samples-bsi/issues/302

2023-09-02 22:03 UTC, CAMOBAP commented
@ronaldtse could you please have a quick look at the CI configuration I'm going to apply this to all public document repositories, I tried to keep it as minimal/clean as possible

2023-09-03 01:10 UTC, ronaldtse requested changes

2023-09-03 01:10 UTC, ronaldtse commented on .github/workflows/docker.yml
> +    if: ${{ github.ref == 'refs/heads/main' }}
There's a way to check the "default Git branch" so it works whether it is main or master.

2023-09-03 01:10 UTC, ronaldtse commented on .github/workflows/docker.yml
> +    branches: [ main ]
Let's use the default git branch:
* https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable

2023-09-03 05:32 UTC, CAMOBAP commented on .github/workflows/docker.yml
> +    if: ${{ github.ref == 'refs/heads/main' }}
good point

2023-09-03 05:32 UTC, CAMOBAP commented on .github/workflows/docker.yml
> +    branches: [ main ]
Unfortunately it will not work for `on` section https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable#comment125403876_68414395

2023-09-03 05:34 UTC, CAMOBAP commented on .github/workflows/docker.yml
> +    branches: [ main ]
Maybe we should leave only `main` here and change it to `main` on all repos if some still use `master`?

2023-09-03 07:31 UTC, CAMOBAP commented on .github/workflows/docker.yml
> +    if: ${{ github.ref == 'refs/heads/main' }}
Done

2023-09-03 07:32 UTC, CAMOBAP commented
@ronaldtse Also for now we upload artifacts for all platforms, it sometimes make sense for troubleshooting propose, should we keep it?

2023-09-03 10:12 UTC, ronaldtse commented on .github/workflows/docker.yml
> +    branches: [ main ]
Instead, can we combine the docker and all other testing workflows into the same workflow file?

The artifacts are uploaded from all platforms. 

When it is the default branch, run the deploy action on the docker artifact.

2023-09-03 10:29 UTC, CAMOBAP commented on .github/workflows/docker.yml
> +    branches: [ main ]
> Instead, can we combine the docker and all other testing workflows into the same workflow file?

we can but it will not increase the code reusability because of the syntax workflow file, we will have to keep two jobs separated and final result will looks like this:

```
name: generate

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  site-gen:
    name: Generate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Metanorma assets
        uses: actions-mn/cache@v1

      - name: Setup Metanorma toolchain
        uses: actions-mn/setup@main

      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@v1
        with:
          agree-to-terms: true
          destination: artifact
          artifact-name: ${{ github.event.repository.name }}-${{ runner.os }}

  docker:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Metanorma assets
        uses: actions-mn/cache@v1

      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@v1
        with:
          agree-to-terms: true

  deploy:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

```

If that's ok, no problem we can go with it, but I assumed that original idea behind this was to make it more clear for non-technical users, to allow them copy-paste this configuration if they need it, i'm not sure that this change make the  the configuration more clear

Anyway last decision up to you

2023-09-04 11:36 UTC, CAMOBAP commented on .github/workflows/docker.yml
> +    branches: [ main ]
@ronaldtse could you please have a quick look

2023-09-04 12:25 UTC, ronaldtse commented on .github/workflows/docker.yml
> +    branches: [ main ]
Let's keep it separate then.

2023-09-04 14:24 UTC, CAMOBAP commented
@ronaldtse ok so it's still ready for review, if we are good to go, I can merge it and proceed with other document repos

2023-09-04 22:05 UTC, merged